"""
Command Executor for Product Lifecycle Orchestrator.

Directly calls core module functions instead of using subprocess.
This improves performance and reliability.
"""
from __future__ import annotations
import shutil
import json
from pathlib import Path
from typing import Optional, Dict, Any

from scripts.core import paths


class CommandExecutor:
    """
    Executes lifecycle commands by directly calling core module functions.

    This replaces the subprocess-based command execution in v2.0,
    improving performance and reducing I/O overhead.
    """

    def __init__(self, project_root: str | Path):
        self.root = Path(project_root).resolve()
        self.lifecycle_dir = self.root / ".lifecycle"
        self.docs_dir = self.root / "Docs"

    # -------------------------------------------------------------------------
    # Command Implementations
    # -------------------------------------------------------------------------

    def execute(self, command: str, args: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Execute a lifecycle command.

        Args:
            command: Command name (e.g., "init", "validate", "outline")
            args: Command arguments

        Returns:
            {
                "success": bool,
                "message": str,
                "data": dict | None,
                "error": str | None
            }
        """
        args = args or {}

        # Route to command handler
        handler_name = f"_cmd_{command}"
        handler = getattr(self, handler_name, None)

        if not handler:
            return {
                "success": False,
                "message": f"Unknown command: {command}",
                "data": None,
                "error": f"No handler for command '{command}'"
            }

        try:
            return handler(args)
        except Exception as e:
            return {
                "success": False,
                "message": f"Command '{command}' failed",
                "data": None,
                "error": str(e)
            }

    # -------------------------------------------------------------------------
    # Command Handlers
    # -------------------------------------------------------------------------

    def _cmd_init(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Initialize project structure.

        Creates:
          - Docs/ directory with INDEX.md
          - .lifecycle/ directory with config.json, dod.json
          - Docs/adr/ directory with INDEX.md
        """
        project_name = args.get("name", self.root.name)

        # Create directories
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        self.lifecycle_dir.mkdir(parents=True, exist_ok=True)
        (self.docs_dir / "adr").mkdir(parents=True, exist_ok=True)
        (self.docs_dir / "product").mkdir(parents=True, exist_ok=True)
        (self.docs_dir / "tech").mkdir(parents=True, exist_ok=True)
        (self.docs_dir / "tests").mkdir(parents=True, exist_ok=True)
        (self.docs_dir / "iterations").mkdir(parents=True, exist_ok=True)
        try:
            from scripts.core.lifecycle_specs import ensure_spec_dirs
            ensure_spec_dirs(self.root)
        except Exception as e:
            print(f"⚠ lifecycle spec schema initialization failed: {e}")

        # Create Docs/INDEX.md
        index_path = self.docs_dir / "INDEX.md"
        if not index_path.exists():
            index_content = f"""# {project_name} - Documentation Index

## Product Documents

- **PRD**: [product/PRD.md](product/PRD.md) — Product Requirements Document
- **UED**: [product/UED.md](product/UED.md) — User Experience Design
- **Architecture**: [tech/ARCH.md](tech/ARCH.md) — Technical Architecture

## Test & Iteration

- **Test Outline**: [tests/MASTER_OUTLINE.md](tests/MASTER_OUTLINE.md) — Test Strategy & Scenarios
- **Iterations**: [iterations/](iterations/) — Iteration Plans & Records
- **Machine Specs**: [.lifecycle/specs/](../.lifecycle/specs/) — Product/UED/Tech/Test Specs and Lifecycle Graph

## Architecture Decisions

- **ADR Index**: [adr/INDEX.md](adr/INDEX.md) — Architecture Decision Records

---

*Generated by Product Lifecycle Orchestrator v2.3*
"""
            index_path.write_text(index_content, encoding="utf-8")

        # Create .lifecycle/config.json
        config_path = self.lifecycle_dir / "config.json"
        if not config_path.exists():
            config = {
                "project_name": project_name,
                "version": "2.3",
                "created_at": self._timestamp(),
                "project_type": "unknown"
            }
            config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

        # Create .lifecycle/dod.json
        dod_path = self.lifecycle_dir / "dod.json"
        if not dod_path.exists():
            dod = {
                "rules": [
                    {
                        "type": "command",
                        "description": "All tests passing",
                        "cmd": "python -m pytest tests/ -q",
                        "required": True
                    },
                    {
                        "type": "coverage",
                        "description": "Code coverage >= 70%",
                        "cmd": "python -m pytest tests/ --cov=scripts --cov-report=term-missing -q",
                        "threshold": 70,
                        "required": False
                    },
                    {
                        "type": "review",
                        "description": "Code review completed (manual)",
                        "manual": True,
                        "required": False
                    }
                ]
            }
            dod_path.write_text(json.dumps(dod, indent=2), encoding="utf-8")

        # Create Docs/adr/INDEX.md
        adr_index_path = self.docs_dir / "adr" / "INDEX.md"
        if not adr_index_path.exists():
            adr_index_content = """# Architecture Decision Records

This directory records architecture decisions for this project.

## Index

| ID | Title | Status | Date |
|----|-------|--------|------|

---

*See [ADR Template](0000-template.md) for creating new ADRs.*
"""
            adr_index_path.write_text(adr_index_content, encoding="utf-8")

        # Create .lifecycle/project_type.json (phases.py phase-5 artifact — initialize with unknown)
        project_type_path = self.lifecycle_dir / "project_type.json"
        if not project_type_path.exists():
            project_type_path.write_text(
                json.dumps({"project_type": "unknown"}, indent=2), encoding="utf-8"
            )

        # Create .lifecycle/iter-1/ with default task_status.json and test_results.json
        # so Phase 12 gate checks don't crash on missing files
        iter1_dir = self.lifecycle_dir / "iter-1"
        iter1_dir.mkdir(parents=True, exist_ok=True)

        task_status_path = iter1_dir / "task_status.json"
        if not task_status_path.exists():
            task_status_path.write_text(
                json.dumps({"tasks": [], "iteration": 1}, indent=2), encoding="utf-8"
            )

        test_results_path = iter1_dir / "test_results.json"
        if not test_results_path.exists():
            test_results_path.write_text(
                json.dumps({"results": {}, "iteration": 1, "timestamp": self._timestamp()}, indent=2),
                encoding="utf-8"
            )

        return {
            "success": True,
            "message": f"Project '{project_name}' initialized successfully",
            "data": {
                "docs_dir": str(self.docs_dir),
                "lifecycle_dir": str(self.lifecycle_dir),
                "adr_dir": str(self.docs_dir / "adr")
            },
            "error": None
        }

    def _cmd_validate(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate a document (PRD, Architecture, or Test Outline).

        Args:
            args["doc"]: Document path (relative to project root)
            args["type"]: Document type ("prd", "architecture", "test-outline", or "auto")
        """
        from scripts.core.doc_validator import validate_document

        doc_path = args.get("doc")
        if not doc_path:
            return {
                "success": False,
                "message": "Missing required argument: doc",
                "data": None,
                "error": "Document path not provided"
            }

        doc_type = args.get("type", "auto")

        # Resolve path
        full_path = self.root / doc_path
        if not full_path.exists():
            return {
                "success": False,
                "message": f"Document not found: {doc_path}",
                "data": None,
                "error": f"File does not exist: {full_path}"
            }

        # Validate
        result = validate_document(str(full_path), doc_type)

        # Create snapshot after successful validation
        if result.get("passed"):
            try:
                from scripts.core.snapshot_manager import SnapshotManager
                snapshot_mgr = SnapshotManager(self.root)
                # Use doc_type as alias (prd or arch) to match phases.py expectations
                snapshot_path = snapshot_mgr.take(doc_path, alias=doc_type, label=f"validated_{doc_type}")
                result["snapshot_path"] = str(snapshot_path)

                # Write score file (phases.py artifact requirement)
                from datetime import datetime, timezone
                score_filename = f"{doc_type}-score.json"
                score_dir = self.root / ".lifecycle" / "steps"
                score_dir.mkdir(parents=True, exist_ok=True)
                score_file = score_dir / score_filename
                score_data = {
                    "score": result.get("score", 0),
                    "threshold": 70,
                    "passed": True,
                    "doc_type": doc_type,
                    "timestamp": datetime.now(timezone.utc).isoformat()
                }
                score_file.write_text(json.dumps(score_data, indent=2), encoding="utf-8")

                # Generate machine specs from approved human docs.
                try:
                    from scripts.core import lifecycle_specs
                    if doc_type == "prd":
                        product_spec = lifecycle_specs.generate_product_spec(self.root, doc_path)
                        result["product_spec_path"] = str(self.root / lifecycle_specs.PRODUCT_SPEC)
                        result["product_requirement_count"] = sum(
                            len(f.get("requirements", [])) for f in product_spec.get("features", [])
                        )
                    elif doc_type in ("arch", "architecture"):
                        lifecycle_specs.generate_tech_spec(self.root, doc_path)
                        lifecycle_specs.generate_lifecycle_graph(self.root)
                        result["tech_spec_path"] = str(self.root / lifecycle_specs.TECH_SPEC)
                        result["lifecycle_graph_path"] = str(self.root / lifecycle_specs.LIFECYCLE_GRAPH)
                except Exception as spec_error:
                    result.setdefault("warnings", []).append(f"machine spec generation failed: {spec_error}")
            except Exception as e:
                # Snapshot creation failed, but validation passed
                print(f"⚠ Snapshot creation failed: {e}")

        return {
            "success": result.get("passed", False),
            "message": f"Document validation {'passed' if result.get('passed') else 'failed'}",
            "data": result,
            "error": result.get("error") if not result.get("passed") else None
        }

    def _cmd_outline(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate test outline from PRD and Architecture.

        Args:
            args["prd"]: PRD document path (default: Docs/product/PRD.md)
            args["arch"]: Architecture document path (default: Docs/architecture/ARCHITECTURE.md)
            args["output"]: Output path (default: Docs/test/MASTER_OUTLINE.md)
        """
        from scripts.core.test_outline import generate_outline, write_outline

        # Resolve paths
        prd_path = args.get("prd", paths.PRD_PATH)
        arch_path = args.get("arch", paths.ARCH_PATH)
        output_path = args.get("output", paths.TEST_OUTLINE_PATH)

        full_prd = self.root / prd_path
        full_arch = self.root / arch_path
        full_output = self.root / output_path

        # Check PRD exists
        if not full_prd.exists():
            return {
                "success": False,
                "message": f"PRD not found: {prd_path}",
                "data": None,
                "error": f"File does not exist: {full_prd}"
            }

        # Generate outline
        try:
            legacy, graph = generate_outline(
                prd_path=str(full_prd),
                arch_path=str(full_arch) if full_arch.exists() else None,
            )

            # Write outline to disk
            full_output.parent.mkdir(parents=True, exist_ok=True)
            write_outline(legacy, str(full_output), test_graph=graph)

            spec_data = {}
            try:
                from scripts.core.lifecycle_specs import generate_all_specs
                spec_data = generate_all_specs(self.root)
            except Exception as spec_error:
                spec_data = {"error": str(spec_error)}

            return {
                "success": True,
                "message": f"Test outline generated: {output_path}",
                "data": {
                    "output_path": str(full_output),
                    "feature_count": len(legacy.get("entries", [])),
                    "scenario_count": legacy.get("total_scenarios", 0),
                    "specs": {
                        "product": paths.PRODUCT_SPEC_JSON,
                        "ued": paths.UED_SPEC_JSON,
                        "tech": paths.TECH_SPEC_JSON,
                        "test": paths.TEST_SPEC_JSON,
                        "lifecycle_graph": paths.LIFECYCLE_GRAPH_JSON,
                        "validation": spec_data.get("validation", spec_data),
                    },
                },
                "error": None
            }
        except Exception as e:
            return {
                "success": False,
                "message": "Failed to generate test outline",
                "data": None,
                "error": str(e) if str(e) else "PRD does not contain recognizable feature sections (expected ### F01 — name format)"
            }

    def _cmd_plan(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate iteration plan from PRD and Architecture.

        Args:
            args["prd"]: PRD document path (default: Docs/product/PRD.md)
            args["arch"]: Architecture document path (default: Docs/tech/ARCH.md)
            args["output-dir"]: Output directory (default: Docs/iterations)
        """
        from scripts.core.iteration_planner import plan_iterations, write_iteration_plans

        # Resolve paths
        prd_path = args.get("prd", paths.PRD_PATH)
        arch_path = args.get("arch", paths.ARCH_PATH)
        output_dir = args.get("output-dir", "Docs/iterations")

        full_prd = self.root / prd_path
        full_arch = self.root / arch_path
        full_output = self.root / output_dir

        # Check PRD exists
        if not full_prd.exists():
            return {
                "success": False,
                "message": f"PRD not found: {prd_path}",
                "data": None,
                "error": f"File does not exist: {full_prd}"
            }

        # Plan iterations
        try:
            iterations = plan_iterations(
                prd_path=str(full_prd),
                arch_path=str(full_arch) if full_arch.exists() else None
            )

            # Ensure output directory exists before writing
            full_output.mkdir(parents=True, exist_ok=True)
            write_iteration_plans(iterations, str(full_output))

            # Initialize velocity tracking (phases.py artifact requirement)
            try:
                from scripts.core.velocity_tracker import VelocityTracker
                VelocityTracker(self.root).initialize(iterations)
            except Exception as e:
                print(f"⚠ velocity.json initialization failed: {e}")

            return {
                "success": True,
                "message": f"Generated {len(iterations)} iteration plans",
                "data": {
                    "iteration_count": len(iterations),
                    "output_dir": str(full_output)
                },
                "error": None
            }
        except Exception as e:
            return {
                "success": False,
                "message": "Failed to generate iteration plans",
                "data": None,
                "error": str(e)
            }

    def _cmd_change(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Detect changes and cascade impacts.

        Args:
            args["change_type"]: Change type (default: "prd-change")
            args["old"]: Old PRD path (optional, uses snapshot if not provided)
            args["new"]: New PRD path (default: Docs/product/PRD.md)
        """
        change_type = args.get("change_type", "prd-change")

        # Handle PRD changes
        if change_type == "prd-change":
            from scripts.core.change_detector import detect_prd_diff

            # Resolve paths
            new_prd = args.get("new", paths.PRD_PATH)
            old_prd = args.get("old")

            full_new = self.root / new_prd

            # Check new PRD exists
            if not full_new.exists():
                return {
                    "success": False,
                    "message": f"PRD not found: {new_prd}",
                    "data": None,
                    "error": f"File does not exist: {full_new}"
                }

            # Detect changes
            try:
                if old_prd:
                    full_old = self.root / old_prd
                    if not full_old.exists():
                        return {
                            "success": False,
                            "message": f"Old PRD not found: {old_prd}",
                            "data": None,
                            "error": f"File does not exist: {full_old}"
                        }

                    result = detect_prd_diff(
                        old_prd_path=str(full_old),
                        new_prd_path=str(full_new)
                    )
                else:
                    # Use snapshot
                    from scripts.core.snapshot_manager import SnapshotManager
                    sm = SnapshotManager(self.root)
                    latest_snapshot = sm.latest_by_alias("prd")
                    if not latest_snapshot:
                        # H5 fix: Graceful degradation when no snapshot exists.
                        # Treat current PRD as first-time change (no baseline to diff against).
                        from datetime import datetime, timezone
                        impact_file = self.lifecycle_dir / "CHANGE_IMPACT.md"
                        impact_file.parent.mkdir(parents=True, exist_ok=True)
                        impact_content = f"""# PRD 变更影响报告

**检测时间**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
**基准快照**: 无（首次变更记录）

## 说明

当前项目尚无 PRD 基准快照，无法执行差异对比分析。
将当前 PRD 视为首次变更版本，已记录本次变更。

## 建议后续步骤

1. 完成 PRD 审核后运行 `./orchestrator run --intent new-product` 完成完整流程
2. 或手动运行 validate 命令创建快照：`python -m scripts validate --doc Docs/product/PRD.md --type prd`
3. 下次变更时将基于本次 PRD 版本做差异分析

## 当前 PRD 路径

`{new_prd}`
"""
                        impact_file.write_text(impact_content, encoding="utf-8")
                        try:
                            from scripts.core.lifecycle_specs import generate_change_impact
                            generate_change_impact(
                                self.root,
                                change_type,
                                user_input=args.get("user_input", "")
                            )
                        except Exception:
                            pass
                        return {
                            "success": True,
                            "message": "No PRD snapshot found — recorded as first-time change",
                            "data": {"changes": [], "no_baseline": True},
                            "error": None
                        }

                    result = detect_prd_diff(
                        old_prd_path=str(latest_snapshot),
                        new_prd_path=str(full_new)
                    )

                # Write CHANGE_IMPACT.md (phases.py artifact requirement)
                from datetime import datetime, timezone
                impact_file = self.lifecycle_dir / "CHANGE_IMPACT.md"
                impact_file.parent.mkdir(parents=True, exist_ok=True)

                # Try cascade_impact for graph-level analysis
                test_graph_path = str(self.lifecycle_dir / "test_graph.json")
                try:
                    from scripts.core.change_detector import cascade_impact
                    impact = cascade_impact(result, test_graph_path)
                    impact_content = impact.get("summary_md", "")
                except Exception:
                    # Fallback: use diff summary only
                    changes = result.get("changes", [])
                    lines = [
                        "# PRD 变更影响报告",
                        "",
                        f"**检测时间**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
                        f"**变更数量**: {len(changes)}",
                        "",
                        "## 变更列表",
                        "",
                    ]
                    for c in changes:
                        lines.append(f"- **{c.get('change_type', 'unknown')}**: {c.get('feature_name', c.get('feature_id', ''))}")
                    impact_content = "\n".join(lines)

                if not impact_content.strip():
                    impact_content = f"# PRD 变更影响报告\n\n变更数: {len(result.get('changes', []))}\n\n（无详细级联分析）\n"
                impact_file.write_text(impact_content, encoding="utf-8")

                try:
                    from scripts.core.lifecycle_specs import generate_change_impact
                    impact = generate_change_impact(
                        self.root,
                        change_type,
                        user_input=args.get("user_input", "")
                    )
                    result["impact"] = impact
                except Exception as spec_error:
                    result["impact_warning"] = str(spec_error)

                return {
                    "success": True,
                    "message": f"Detected {len(result.get('changes', []))} changes",
                    "data": result,
                    "error": None
                }
            except Exception as e:
                return {
                    "success": False,
                    "message": "Failed to detect changes",
                    "data": None,
                    "error": str(e)
                }

        # Handle code changes (model-driven) — scan project for context
        elif change_type in ("code-change", "bug-fix", "gap", "test-failure"):
            from datetime import datetime, timezone
            impact_file = self.lifecycle_dir / "CHANGE_IMPACT.md"
            impact_file.parent.mkdir(parents=True, exist_ok=True)

            # Scan project for context (files modified recently, test status)
            project_context = ""
            try:
                from scripts.adapters.project_scanner import scan_project
                scan_result = scan_project(str(self.root))
                recent_files = scan_result.get("recent_files", [])[:10]
                if recent_files:
                    project_context += "\n## 最近修改的文件\n\n"
                    for f in recent_files:
                        project_context += f"- `{f}`\n"
                test_status = scan_result.get("test_status", "")
                if test_status:
                    project_context += f"\n## 测试状态\n\n{test_status}\n"
            except Exception:
                pass  # Scanner not available

            impact_content = f"""# 变更记录

**变更类型**: {change_type}
**记录时间**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

## 说明

此变更由模型驱动，具体修改内容见 git 提交记录。

### 变更类型说明

- `bug-fix`：缺陷修复，不影响 PRD 功能需求
- `code-change`：代码重构或优化，不改变外部行为
- `test-failure`：测试失败修复
- `gap`：补齐缺失实现
{project_context}

## 后续步骤

1. 确认修改通过所有测试
2. 如有必要，更新测试大纲
3. 继续执行 DoD 检查
"""
            impact_file.write_text(impact_content, encoding="utf-8")
            try:
                from scripts.core.lifecycle_specs import generate_change_impact
                generate_change_impact(
                    self.root,
                    change_type,
                    user_input=args.get("user_input", "")
                )
            except Exception:
                pass

            return {
                "success": True,
                "message": f"Code change detected: {change_type}",
                "data": {
                    "change_type": change_type,
                    "instructions": "Model should handle code changes interactively"
                },
                "error": None
            }

        # Handle other change types
        else:
            # Write CHANGE_IMPACT.md (phases.py artifact requirement)
            from datetime import datetime, timezone
            impact_file = self.lifecycle_dir / "CHANGE_IMPACT.md"
            impact_file.parent.mkdir(parents=True, exist_ok=True)
            impact_content = f"""# 变更记录

**变更类型**: {change_type}
**记录时间**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

## 说明

此变更由模型驱动，具体修改内容见 git 提交记录。

## 后续步骤

1. 确认修改通过所有测试
2. 如有必要，更新测试大纲
3. 继续执行 DoD 检查
"""
            impact_file.write_text(impact_content, encoding="utf-8")
            try:
                from scripts.core.lifecycle_specs import generate_change_impact
                generate_change_impact(
                    self.root,
                    change_type,
                    user_input=args.get("user_input", "")
                )
            except Exception:
                pass

            return {
                "success": True,
                "message": f"Change detected: {change_type}",
                "data": {
                    "change_type": change_type
                },
                "error": None
            }

    def _cmd_draft(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate draft document (PRD or Architecture).

        This is a placeholder that returns instructions for the model.
        The actual drafting is done by the model interactively.

        Args:
            args["type"]: Document type ("prd" or "architecture")
        """
        doc_type = args.get("doc_type", args.get("type", "prd"))

        if doc_type == "prd":
            # Try to generate a structured draft prompt using prd_drafter
            draft_prompt = None
            try:
                from scripts.core.prd_drafter import generate_draft_prompt
                user_desc = args.get("user_description", args.get("description", ""))
                draft_prompt = generate_draft_prompt(user_desc)
            except Exception:
                pass  # Graceful degradation: no data available yet

            data: Dict[str, Any] = {
                "instructions": "Model should generate PRD draft interactively",
                "output_path": paths.PRD_PATH
            }
            if draft_prompt:
                data["draft_prompt"] = draft_prompt

            return {
                "success": True,
                "message": "PRD draft mode activated",
                "data": data,
                "error": None
            }
        elif doc_type in ("ued", "ux", "interaction"):
            data = {
                "instructions": "Model should generate UED draft interactively",
                "output_path": paths.UED_PATH,
            }
            return {
                "success": True,
                "message": "UED draft mode activated",
                "data": data,
                "error": None
            }
        elif doc_type in ("arch", "architecture"):
            # Try to generate a structured draft prompt using arch_drafter
            draft_prompt = None
            try:
                from scripts.core.arch_drafter import generate_draft_prompt
                draft_prompt = generate_draft_prompt(str(self.root))
            except Exception:
                pass  # Graceful degradation: no interview data or import error

            data: Dict[str, Any] = {
                "instructions": "Model should generate Architecture draft interactively",
                "output_path": paths.ARCH_PATH,  # Align with phases.py Phase 6 artifact
            }
            if draft_prompt:
                data["draft_prompt"] = draft_prompt

            return {
                "success": True,
                "message": "Architecture draft mode activated",
                "data": data,
                "error": None
            }
        else:
            return {
                "success": False,
                "message": f"Unknown document type: {doc_type}",
                "data": None,
                "error": "Valid types: prd, ued, architecture"
            }

    def _cmd_gate(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Check Definition of Done for an iteration.

        Performs two validation layers:
        1. Artifact validation (PRD existence, iteration artifacts, test records)
        2. DoD rule checks (tasks, tests, commands, coverage, review)

        Args:
            args["iteration"]: Iteration number
        """
        from scripts.core.dod_checker import DoDChecker

        iteration_n = args.get("iteration")
        if not iteration_n:
            return {
                "success": False,
                "message": "Missing required argument: iteration",
                "data": None,
                "error": "Iteration number not provided"
            }

        # Create iter-N directory and default files if they don't exist
        iter_dir = self.lifecycle_dir / f"iter-{iteration_n}"
        iter_dir.mkdir(parents=True, exist_ok=True)

        task_status_path = iter_dir / "task_status.json"
        if not task_status_path.exists():
            task_status_path.write_text(
                json.dumps({"tasks": [], "iteration": iteration_n}, indent=2),
                encoding="utf-8"
            )

        test_results_path = iter_dir / "test_results.json"
        if not test_results_path.exists():
            test_results_path.write_text(
                json.dumps({"results": {}, "iteration": iteration_n}, indent=2),
                encoding="utf-8"
            )

        try:
            # Layer 1: Artifact validation
            artifact_result = {"passed": True, "blocking_failures": []}
            try:
                from scripts.core.artifact_validator import validate_iteration
                artifact_result = validate_iteration(self.root, iteration_n)
                if not artifact_result.get("passed", True):
                    print(f"[GATE] Artifact validation failed:")
                    for f in artifact_result.get("blocking_failures", []):
                        print(f"  ✗ {f}")
            except ImportError:
                print("[GATE] ⚠ artifact_validator not available, skipping artifact checks")
                artifact_result = {"passed": False, "blocking_failures": ["artifact_validator module not available"]}

            # Layer 2: DoD rule checks
            checker = DoDChecker(self.root)
            results = checker.run_all(iteration=iteration_n)
            passed = all(r.get("status") in ("pass", "warn", "deferred") for r in results)
            warns = [r for r in results if r.get("status") in ("warn", "deferred")]
            if warns:
                print(f"[WARN] DoD check has {len(warns)} deferred/unverified item(s):")
                for w in warns:
                    print(f"  ⚠ {w['rule']}: {w['detail']}")

            # Combine: gate passes only if both layers pass
            gate_passed = passed and artifact_result.get("passed", True)

            return {
                "success": gate_passed,
                "message": f"Gate check {'passed' if gate_passed else 'failed'} for iteration {iteration_n}",
                "data": {
                    "dod_results": results,
                    "artifact_validation": artifact_result,
                },
                "error": None
            }
        except Exception as e:
            return {
                "success": False,
                "message": f"Failed to check gate for iteration {iteration_n}",
                "data": None,
                "error": str(e)
            }

    def _cmd_specs(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate or validate lifecycle machine specs.

        Args:
            args["action"]: "generate" or "validate" (default: "generate")
            args["target"]: "all", "product", "ued", "tech", "test", "graph" (default: "all")
        """
        from scripts.core import lifecycle_specs

        action = args.get("action", "generate")
        target = args.get("target", "all")

        if action == "validate":
            result = lifecycle_specs.validate_specs(self.root)
            return {
                "success": result.get("passed", False),
                "message": "Lifecycle specs validation passed" if result.get("passed") else "Lifecycle specs validation failed",
                "data": result,
                "error": None if result.get("passed") else "Spec validation failed",
            }

        generated: Dict[str, Any] = {}
        if target in ("all", "product"):
            generated["product"] = lifecycle_specs.generate_product_spec(self.root)
        if target in ("all", "ued"):
            generated["ued"] = lifecycle_specs.generate_ued_spec(self.root)
        if target in ("all", "tech"):
            generated["tech"] = lifecycle_specs.generate_tech_spec(self.root)
        if target in ("all", "test"):
            generated["test"] = lifecycle_specs.generate_test_spec(self.root)
        if target in ("all", "graph"):
            generated["graph"] = lifecycle_specs.generate_lifecycle_graph(self.root)

        validation = lifecycle_specs.validate_specs(self.root)
        generated["validation"] = validation

        # Intermediate spec phases intentionally generate one target at a time.
        # Full cross-spec validation is only a hard gate for target=all.
        if target == "all":
            success = validation.get("passed", False)
            error = None if success else "Generated specs failed validation"
        else:
            success = target in generated
            error = None if success else f"Unknown spec target: {target}"
        return {
            "success": success,
            "message": "Lifecycle specs generated",
            "data": generated,
            "error": error,
        }

    def _cmd_analyze_solution(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        分析实现方案

        Args:
            args: {"intent": "bug-fix", "user_input": "修复登录失败"}

        Returns:
            {
                "success": bool,
                "message": str,
                "data": {
                    "project_context": {...},
                    "industry_solutions": [...],
                    "proposed_solutions": [...],
                    "recommendation": str,
                    "confidence": float
                },
                "error": str | None
            }
        """
        from scripts.core.solution_analyzer import SolutionAnalyzer

        intent = args.get("intent")
        user_input = args.get("user_input")

        analyzer = SolutionAnalyzer(self.root)
        result = analyzer.analyze(intent, user_input)

        # 保存结果到 .lifecycle/solution.json
        solution_file = self.lifecycle_dir / "solution.json"
        solution_file.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")

        return {
            "success": True,
            "message": "方案分析完成",
            "data": result,
            "error": None
        }

    # -------------------------------------------------------------------------
    # Helper Methods
    # -------------------------------------------------------------------------

    def _timestamp(self) -> str:
        """Get current timestamp in ISO format."""
        from datetime import datetime, timezone
        return datetime.now(timezone.utc).isoformat()
