"""
Command Executor for Product-Lifecycle Orchestrator.

Directly calls core module functions instead of using subprocess.
This improves performance and reliability.
"""
from __future__ import annotations
import shutil
import json
from pathlib import Path
from typing import Optional, Dict, Any


class CommandExecutor:
    """
    Executes lifecycle commands by directly calling core module functions.

    This replaces the subprocess-based command execution in v2.0,
    improving performance and reducing I/O overhead.
    """

    def __init__(self, project_root: str | Path):
        self.root = Path(project_root).resolve()
        self.lifecycle_dir = self.root / ".lifecycle"
        self.docs_dir = self.root / "Docs"

    # -------------------------------------------------------------------------
    # Command Implementations
    # -------------------------------------------------------------------------

    def execute(self, command: str, args: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Execute a lifecycle command.

        Args:
            command: Command name (e.g., "init", "validate", "outline")
            args: Command arguments

        Returns:
            {
                "success": bool,
                "message": str,
                "data": dict | None,
                "error": str | None
            }
        """
        args = args or {}

        # Route to command handler
        handler_name = f"_cmd_{command}"
        handler = getattr(self, handler_name, None)

        if not handler:
            return {
                "success": False,
                "message": f"Unknown command: {command}",
                "data": None,
                "error": f"No handler for command '{command}'"
            }

        try:
            return handler(args)
        except Exception as e:
            return {
                "success": False,
                "message": f"Command '{command}' failed",
                "data": None,
                "error": str(e)
            }

    # -------------------------------------------------------------------------
    # Command Handlers
    # -------------------------------------------------------------------------

    def _cmd_init(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Initialize project structure.

        Creates:
          - Docs/ directory with INDEX.md
          - .lifecycle/ directory with config.json, dod.json
          - Docs/adr/ directory with INDEX.md
        """
        project_name = args.get("name", self.root.name)

        # Create directories
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        self.lifecycle_dir.mkdir(parents=True, exist_ok=True)
        (self.docs_dir / "adr").mkdir(parents=True, exist_ok=True)

        # Create Docs/INDEX.md
        index_path = self.docs_dir / "INDEX.md"
        if not index_path.exists():
            index_content = f"""# {project_name} - Documentation Index

## Product Documents

- **PRD**: [product/PRD.md](product/PRD.md) — Product Requirements Document
- **Architecture**: [architecture/ARCHITECTURE.md](architecture/ARCHITECTURE.md) — Technical Architecture

## Test & Iteration

- **Test Outline**: [test/MASTER_OUTLINE.md](test/MASTER_OUTLINE.md) — Test Strategy & Scenarios
- **Iterations**: [iterations/](iterations/) — Iteration Plans & Records

## Architecture Decisions

- **ADR Index**: [adr/INDEX.md](adr/INDEX.md) — Architecture Decision Records

---

*Generated by Product-Lifecycle v2.1*
"""
            index_path.write_text(index_content, encoding="utf-8")

        # Create .lifecycle/config.json
        config_path = self.lifecycle_dir / "config.json"
        if not config_path.exists():
            config = {
                "project_name": project_name,
                "version": "2.1",
                "created_at": self._timestamp(),
                "project_type": "unknown"
            }
            config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

        # Create .lifecycle/dod.json
        dod_path = self.lifecycle_dir / "dod.json"
        if not dod_path.exists():
            dod = {
                "rules": [
                    {
                        "id": "tasks-complete",
                        "description": "All planned tasks completed",
                        "check": "task_registry.check_all_complete(iteration_n)",
                        "required": True
                    },
                    {
                        "id": "tests-pass",
                        "description": "All tests passing",
                        "check": "artifact_validator.all_tests_passing(iteration_n)",
                        "required": True
                    },
                    {
                        "id": "lint-clean",
                        "description": "No linting errors",
                        "check": "artifact_validator.lint_clean(iteration_n)",
                        "required": False
                    },
                    {
                        "id": "coverage-met",
                        "description": "Code coverage meets threshold",
                        "check": "artifact_validator.coverage_threshold(iteration_n, 80)",
                        "required": False
                    },
                    {
                        "id": "review-done",
                        "description": "Code review completed",
                        "check": "artifact_validator.review_completed(iteration_n)",
                        "required": False
                    }
                ]
            }
            dod_path.write_text(json.dumps(dod, indent=2), encoding="utf-8")

        # Create Docs/adr/INDEX.md
        adr_index_path = self.docs_dir / "adr" / "INDEX.md"
        if not adr_index_path.exists():
            adr_index_content = """# Architecture Decision Records

This directory records architecture decisions for this project.

## Index

| ID | Title | Status | Date |
|----|-------|--------|------|

---

*See [ADR Template](0000-template.md) for creating new ADRs.*
"""
            adr_index_path.write_text(adr_index_content, encoding="utf-8")

        return {
            "success": True,
            "message": f"Project '{project_name}' initialized successfully",
            "data": {
                "docs_dir": str(self.docs_dir),
                "lifecycle_dir": str(self.lifecycle_dir),
                "adr_dir": str(self.docs_dir / "adr")
            },
            "error": None
        }

    def _cmd_validate(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate a document (PRD, Architecture, or Test Outline).

        Args:
            args["doc"]: Document path (relative to project root)
            args["type"]: Document type ("prd", "architecture", "test-outline", or "auto")
        """
        from scripts.core.doc_validator import validate_document

        doc_path = args.get("doc")
        if not doc_path:
            return {
                "success": False,
                "message": "Missing required argument: doc",
                "data": None,
                "error": "Document path not provided"
            }

        doc_type = args.get("type", "auto")

        # Resolve path
        full_path = self.root / doc_path
        if not full_path.exists():
            return {
                "success": False,
                "message": f"Document not found: {doc_path}",
                "data": None,
                "error": f"File does not exist: {full_path}"
            }

        # Validate
        result = validate_document(str(full_path), doc_type)

        # Create snapshot after successful validation
        if result.get("passed"):
            try:
                from scripts.core.snapshot_manager import SnapshotManager
                snapshot_mgr = SnapshotManager(self.root)
                snapshot_path = snapshot_mgr.take(doc_path, label=f"validated_{doc_type}")
                result["snapshot_path"] = str(snapshot_path)
            except Exception as e:
                # Snapshot creation failed, but validation passed
                print(f"⚠ Snapshot creation failed: {e}")

        return {
            "success": result.get("passed", False),
            "message": f"Document validation {'passed' if result.get('passed') else 'failed'}",
            "data": result,
            "error": result.get("error") if not result.get("passed") else None
        }

    def _cmd_outline(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate test outline from PRD and Architecture.

        Args:
            args["prd"]: PRD document path (default: Docs/product/PRD.md)
            args["arch"]: Architecture document path (default: Docs/architecture/ARCHITECTURE.md)
            args["output"]: Output path (default: Docs/test/MASTER_OUTLINE.md)
        """
        from scripts.core.test_outline import generate_outline, write_outline

        # Resolve paths
        prd_path = args.get("prd", "Docs/product/PRD.md")
        arch_path = args.get("arch", "Docs/architecture/ARCHITECTURE.md")
        output_path = args.get("output", "Docs/test/MASTER_OUTLINE.md")

        full_prd = self.root / prd_path
        full_arch = self.root / arch_path
        full_output = self.root / output_path

        # Check PRD exists
        if not full_prd.exists():
            return {
                "success": False,
                "message": f"PRD not found: {prd_path}",
                "data": None,
                "error": f"File does not exist: {full_prd}"
            }

        # Generate outline
        try:
            outline = generate_outline(
                prd_path=str(full_prd),
                arch_path=str(full_arch) if full_arch.exists() else None,
                output_path=str(full_output)
            )

            return {
                "success": True,
                "message": f"Test outline generated: {output_path}",
                "data": {
                    "output_path": str(full_output),
                    "feature_count": len(outline.get("features", [])),
                    "scenario_count": sum(len(s) for s in outline.get("scenarios", {}).values())
                },
                "error": None
            }
        except Exception as e:
            return {
                "success": False,
                "message": "Failed to generate test outline",
                "data": None,
                "error": str(e)
            }

    def _cmd_plan(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate iteration plan from test outline.

        Args:
            args["outline"]: Test outline path (default: Docs/test/MASTER_OUTLINE.md)
            args["output-dir"]: Output directory (default: Docs/iterations)
            args["velocity"]: Velocity points per iteration (default: 10)
        """
        from scripts.core.iteration_planner import plan_iterations, write_iteration_plans

        # Resolve paths
        outline_path = args.get("outline", "Docs/test/MASTER_OUTLINE.md")
        output_dir = args.get("output-dir", "Docs/iterations")
        velocity = args.get("velocity", 10)

        full_outline = self.root / outline_path
        full_output = self.root / output_dir

        # Check outline exists
        if not full_outline.exists():
            return {
                "success": False,
                "message": f"Test outline not found: {outline_path}",
                "data": None,
                "error": f"File does not exist: {full_outline}"
            }

        # Plan iterations
        try:
            iterations = plan_iterations(
                outline_path=str(full_outline),
                velocity=velocity
            )

            write_iteration_plans(iterations, str(full_output))

            return {
                "success": True,
                "message": f"Generated {len(iterations)} iteration plans",
                "data": {
                    "iteration_count": len(iterations),
                    "output_dir": str(full_output)
                },
                "error": None
            }
        except Exception as e:
            return {
                "success": False,
                "message": "Failed to generate iteration plans",
                "data": None,
                "error": str(e)
            }

    def _cmd_change(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Detect PRD changes and cascade impacts.

        Args:
            args["old"]: Old PRD path (optional, uses snapshot if not provided)
            args["new"]: New PRD path (default: Docs/product/PRD.md)
        """
        from scripts.core.change_detector import detect_prd_diff

        # Resolve paths
        new_prd = args.get("new", "Docs/product/PRD.md")
        old_prd = args.get("old")

        full_new = self.root / new_prd

        # Check new PRD exists
        if not full_new.exists():
            return {
                "success": False,
                "message": f"PRD not found: {new_prd}",
                "data": None,
                "error": f"File does not exist: {full_new}"
            }

        # Detect changes
        try:
            if old_prd:
                full_old = self.root / old_prd
                if not full_old.exists():
                    return {
                        "success": False,
                        "message": f"Old PRD not found: {old_prd}",
                        "data": None,
                        "error": f"File does not exist: {full_old}"
                    }

                result = detect_prd_diff(
                    old_prd_path=str(full_old),
                    new_prd_path=str(full_new)
                )
            else:
                # Use snapshot
                snapshot_dir = self.lifecycle_dir / "snapshots"
                if not snapshot_dir.exists():
                    return {
                        "success": False,
                        "message": "No snapshot found",
                        "data": None,
                        "error": "Please provide --old or create a snapshot first"
                    }

                # Find latest PRD snapshot
                snapshots = sorted(snapshot_dir.glob("prd-*.md"))
                if not snapshots:
                    return {
                        "success": False,
                        "message": "No PRD snapshot found",
                        "data": None,
                        "error": "No PRD snapshots in .lifecycle/snapshots/"
                    }

                latest_snapshot = snapshots[-1]
                result = detect_prd_diff(
                    old_prd_path=str(latest_snapshot),
                    new_prd_path=str(full_new)
                )

            return {
                "success": True,
                "message": f"Detected {len(result.get('changes', []))} changes",
                "data": result,
                "error": None
            }
        except Exception as e:
            return {
                "success": False,
                "message": "Failed to detect changes",
                "data": None,
                "error": str(e)
            }

    def _cmd_draft(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate draft document (PRD or Architecture).

        This is a placeholder that returns instructions for the model.
        The actual drafting is done by the model interactively.

        Args:
            args["type"]: Document type ("prd" or "architecture")
        """
        doc_type = args.get("type", "prd")

        if doc_type == "prd":
            return {
                "success": True,
                "message": "PRD draft mode activated",
                "data": {
                    "instructions": "Model should generate PRD draft interactively",
                    "output_path": "Docs/product/PRD.md"
                },
                "error": None
            }
        elif doc_type == "architecture":
            return {
                "success": True,
                "message": "Architecture draft mode activated",
                "data": {
                    "instructions": "Model should generate Architecture draft interactively",
                    "output_path": "Docs/architecture/ARCHITECTURE.md"
                },
                "error": None
            }
        else:
            return {
                "success": False,
                "message": f"Unknown document type: {doc_type}",
                "data": None,
                "error": "Valid types: prd, architecture"
            }

    def _cmd_gate(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Check Definition of Done for an iteration.

        Args:
            args["iteration"]: Iteration number
        """
        from scripts.core.dod_checker import DoDChecker

        iteration_n = args.get("iteration")
        if not iteration_n:
            return {
                "success": False,
                "message": "Missing required argument: iteration",
                "data": None,
                "error": "Iteration number not provided"
            }

        try:
            checker = DoDChecker(self.root)
            results = checker.run_all(iteration=iteration_n)
            passed = all(r.get("passed", False) for r in results)

            return {
                "success": passed,
                "message": f"DoD check {'passed' if passed else 'failed'} for iteration {iteration_n}",
                "data": {"results": results},
                "error": None
            }
        except Exception as e:
            return {
                "success": False,
                "message": f"Failed to check DoD for iteration {iteration_n}",
                "data": None,
                "error": str(e)
            }

    # -------------------------------------------------------------------------
    # Helper Methods
    # -------------------------------------------------------------------------

    def _timestamp(self) -> str:
        """Get current timestamp in ISO format."""
        from datetime import datetime, timezone
        return datetime.now(timezone.utc).isoformat()
