# Auto-generated by skill-architect. DO NOT edit manually.
# Source: skill_definition.json

STEPS = [
    {"id": 'project-bootstrapped', "description": '初始化：文档结构 + DoD配置 + Risk Register + ADR目录', "required": True},
    {"id": 'prd-drafted', "description": 'AI协作起草PRD初稿（Claude生成 → 用户审核修改）', "required": True},
    {"id": 'prd-validated', "description": 'PRD验证通过 + 自动快照（无需手动备份）', "required": True},
    {"id": 'arch-designed', "description": 'AI协作架构设计：项目类型识别 + ADR初稿 + 架构草案', "required": True},
    {"id": 'arch-validated', "description": '架构验证 + ADR注册 + 快照', "required": True},
    {"id": 'test-outline-ready', "description": '自适应测试大纲：按项目类型选维度（Web/CLI/Mobile/Data/Microservices）', "required": True},
    {"id": 'iterations-planned', "description": 'Velocity感知迭代规划：每迭代有E2E验收标准 + 工时估算', "required": True},
]

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

_WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
CANCEL_FILE = _WORKSPACE_ROOT / ".lifecycle" / ".skill-cancel"
STEPS_DIR = _WORKSPACE_ROOT / ".lifecycle" / "steps"


def _step_file(step_id):
    return STEPS_DIR / "{}.json".format(step_id)


def _valid_ids():
    return {s["id"] for s in STEPS}


def _is_required(step_id):
    for s in STEPS:
        if s["id"] == step_id:
            return s.get("required", True)
    return True


def _check_cancel():
    if CANCEL_FILE.exists():
        print("[enforcer] Workflow cancelled by user. Exiting gracefully.")
        sys.exit(0)


def record(step_id, data=None):
    if step_id not in _valid_ids():
        raise ValueError("Unknown step {}. Valid IDs: {}".format(step_id, sorted(_valid_ids())))
    STEPS_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = {
        "step": step_id,
        "completed_at": datetime.now(timezone.utc).isoformat(),
        "data": data or {},
    }
    path = _step_file(step_id)
    path.write_text(json.dumps(checkpoint, indent=2))
    return path


def check(step_id):
    return _step_file(step_id).exists()


def require(step_id):
    _check_cancel()
    if not _is_required(step_id):
        return {}
    if not check(step_id):
        print("\n[enforcer] HALT: Required step {} has NOT been recorded.".format(step_id))
        print("  Complete this step, then record it:")
        print("    python scripts/step_enforcer.py record {}".format(step_id))
        sys.exit(1)
    try:
        return json.loads(_step_file(step_id).read_text())
    except (ValueError, OSError):
        return {}


def status():
    _check_cancel()
    print("[enforcer] Step Status")
    print("=" * 50)
    for step in STEPS:
        sid = step["id"]
        done = check(sid)
        req_label = "" if step.get("required", True) else " (optional)"
        status_icon = "+" if done else "o"
        print("  {} {}{}".format(status_icon, sid, req_label))


def reset(step_id):
    f = _step_file(step_id)
    if f.exists():
        f.unlink()
        print("[enforcer] Reset: {}".format(step_id))
    else:
        print("[enforcer] Not recorded: {}".format(step_id))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python step_enforcer.py <require|record|status|reset|cancel-check> [step-id]")
        sys.exit(1)
    cmd = sys.argv[1]
    if cmd == "require":
        require(sys.argv[2])
    elif cmd == "record":
        data = json.loads(sys.argv[3]) if len(sys.argv) > 3 else None
        record(sys.argv[2], data)
        print("[enforcer] Recorded: {}".format(sys.argv[2]))
    elif cmd == "status":
        status()
    elif cmd == "reset":
        reset(sys.argv[2])
    elif cmd == "cancel-check":
        _check_cancel()
        print("[enforcer] No cancel flag detected.")
    else:
        print("Unknown command: {}".format(cmd))
        sys.exit(1)
